{
  "openapi": "3.0.0",
  "info": {
    "title": "TrotoTrack",
    "description": "TrotoTrack API Documentation",
    "version": "1.0.0",
    "contact": {
      "name": "TrotoTrack",
      "url": "https://trototrack.my.id",
      "email": "shiigetsu1@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8080/",
      "description": "User Documentation"
    }
  ],
  "externalDocs": {
    "description": "Find out more about TrotoTrack",
    "url": "https://trototrack.my.id"
  },
  "paths": {
    "/login": {
      "post": {
        "tags": ["Login & Register"],
        "summary": "Login to the application",
        "description": "Login to the application",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestLogin"
              },
              "examples": {
                "login": {
                  "value": {
                    "email": "hilal@gmail.com",
                    "password": "123456asd"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseLogin"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": true,
                      "message": "Login success",
                      "data": {
                        "name": "hilal",
                        "email": "hilal@gmail.com",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkhpbGFsIiwiZW1haWwiOiJoaWxhbEBnbWFpbC5jb20iLCJpYXQiOjE1MTYyMzkwMjJ9.7J1"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "missing_fields": {
                    "value": {
                      "status": false,
                      "message": "Please fill all required fields"
                    }
                  },
                  "invalid_email": {
                    "value": {
                      "status": false,
                      "message": "Email is not valid"
                    }
                  },
                  "incorrect_password": {
                    "value": {
                      "status": false,
                      "message": "Password is incorrect"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "not_found": {
                    "value": {
                      "status": false,
                      "message": "Email not registered"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "server_error": {
                    "value": {
                      "status": false,
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "tags": ["Login & Register"],
        "summary": "Register to the application",
        "description": "Register to the application",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestRegister"
              },
              "examples": {
                "register": {
                  "value": {
                    "name": "troto",
                    "username": "troto",
                    "email": "troto@gmail.com",
                    "password": "123456asd",
                    "confirm_password": "123456asd"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Register success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCreateUpdateDelete"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": true,
                      "message": "Success created data"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCreateUpdateDelete"
                },
                "examples": {
                  "missing_fields": {
                    "value": {
                      "status": false,
                      "message": "Please fill all required fields"
                    }
                  },
                  "password_length": {
                    "value": {
                      "status": false,
                      "message": "Password must be at least 8 characters long"
                    }
                  },
                  "password_mismatch": {
                    "value": {
                      "status": false,
                      "message": "Password and Confirm Password must be the same"
                    }
                  },
                  "invalid_email": {
                    "value": {
                      "status": false,
                      "message": "Email is not valid"
                    }
                  },
                  "email_registered": {
                    "value": {
                      "status": false,
                      "message": "Email already registered"
                    }
                  },
                  "username_exists": {
                    "value": {
                      "status": false,
                      "message": "Username already exists"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCreateUpdateDelete"
                },
                "examples": {
                  "server_error": {
                    "value": {
                      "status": false,
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "security": [
          {
            "auth": []
          }
        ],
        "tags": ["Profile"],
        "summary": "Get profile user",
        "description": "Get profile user",
        "responses": {
          "200": {
            "description": "Get profile user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseGetUser"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": true,
                      "message": "Success get data",
                      "data": {
                        "id": "07546e64-f4da-4c77-9625-df1fbc536d1e",
                        "name": "hilal",
                        "email": "hilal@gmail.com"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "missing_id": {
                    "value": {
                      "status": false,
                      "message": "ID is required"
                    }
                  },
                  "invalid_id": {
                    "value": {
                      "status": false,
                      "message": "ID is not valid"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "unauthorized": {
                    "value": {
                      "status": false,
                      "message": "Unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "not_found": {
                    "value": {
                      "status": false,
                      "message": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "server_error": {
                    "value": {
                      "status": false,
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "auth": []
          }
        ],
        "tags": ["Profile"],
        "summary": "Update user profile",
        "description": "Update user profile",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestUpdateUser"
              },
              "examples": {
                "update": {
                  "value": {
                    "name": "hilal",
                    "username": "hilal",
                    "email": "hilal@gmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Update user profile",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCreateUpdateDelete"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": true,
                      "message": "Success updated data"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "missing_id": {
                    "value": {
                      "status": false,
                      "message": "ID is required"
                    }
                  },
                  "invalid_id": {
                    "value": {
                      "status": false,
                      "message": "ID is not valid"
                    }
                  },
                  "invalid_email": {
                    "value": {
                      "status": false,
                      "message": "Email is not valid"
                    }
                  },
                  "email_registered": {
                    "value": {
                      "status": false,
                      "message": "Email already registered"
                    }
                  },
                  "username_exists": {
                    "value": {
                      "status": false,
                      "message": "Username already exists"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "unauthorized": {
                    "value": {
                      "status": false,
                      "message": "Unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "not_found": {
                    "value": {
                      "status": false,
                      "message": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "server_error": {
                    "value": {
                      "status": false,
                      "message": "Internal Server Error"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "security": [
          {
            "auth": []
          }
        ],
        "tags": ["Profile"],
        "summary": "Update password user",
        "description": "Update password user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestUpdatePasswordUser"
              },
              "examples": {
                "update": {
                  "value": {
                    "old_password": "123456asd",
                    "new_password": "troto123456",
                    "confirm_password": "troto123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Update password user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCreateUpdateDelete"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": true,
                      "message": "Success updated password"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "missing_fields": {
                    "value": {
                      "status": false,
                      "message": "Please fill all required fields"
                    }
                  },
                  "invalid_id": {
                    "value": {
                      "status": false,
                      "message": "ID is not valid"
                    }
                  },
                  "short_password": {
                    "value": {
                      "status": false,
                      "message": "Password must be at least 8 characters long"
                    }
                  },
                  "password_mismatch": {
                    "value": {
                      "status": false,
                      "message": "Password and Confirm Password must be the same"
                    }
                  },
                  "incorrect_old_password": {
                    "value": {
                      "status": false,
                      "message": "Old password is incorrect"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "unauthorized": {
                    "value": {
                      "status": false,
                      "message": "Unauthorized"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "forbidden": {
                    "value": {
                      "status": false,
                      "message": "Forbidden access"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "not_found": {
                    "value": {
                      "status": false,
                      "message": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "server_error": {
                    "value": {
                      "status": false,
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/articles": {
      "get": {
        "tags": ["Article"],
        "summary": "Get all article",
        "description": "Get all article",
        "responses": {
          "200": {
            "description": "Get all article",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseArticle"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": true,
                      "message": "Success get all data",
                      "data": [
                        {
                          "id": "07546e64-f4da-4c77-9625-df1fbc536d1e",
                          "title": "Bumi Sementara",
                          "description": "Bumi sementara adalah bumi yang kita tempati sekarang",
                          "image": "https://trototrack.my.id/image.jpg",
                          "created_at": "2021-08-01T00:00:00Z"
                        },
                        {
                          "id": "07546e64-f4da-4c77-9625-df1fbc536d1e",
                          "title": "Bumi Sementara",
                          "description": "Bumi sementara adalah bumi yang kita tempati sekarang",
                          "image": "https://trototrack.my.id/image.jpg",
                          "created_at": "2021-08-01T00:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "unauthorized": {
                    "value": {
                      "status": false,
                      "message": "Unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "not_found": {
                    "value": {
                      "status": false,
                      "message": "No article found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "server_error": {
                    "value": {
                      "status": false,
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/articles/{id}": {
      "get": {
        "tags": ["Article"],
        "summary": "Get article by id",
        "description": "Get article by id",
        "parameters": [
          {
            "$ref": "#/components/parameters/ArticleId"
          }
        ],
        "responses": {
          "200": {
            "description": "Get article by id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseArticle"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": true,
                      "message": "Success get data",
                      "data": {
                        "id": "07546e64-f4da-4c77-9625-df1fbc536d1e",
                        "title": "Bumi Sementara",
                        "description": "Bumi sementara adalah bumi yang kita tempati sekarang",
                        "image": "https://trototrack.my.id/image.jpg",
                        "created_at": "2021-08-01T00:00:00Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "missing_id": {
                    "value": {
                      "status": false,
                      "message": "ID is required"
                    }
                  },
                  "invalid_id": {
                    "value": {
                      "status": false,
                      "message": "ID is not valid"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "unauthorized": {
                    "value": {
                      "status": false,
                      "message": "Unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "not_found": {
                    "value": {
                      "status": false,
                      "message": "Article not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                },
                "examples": {
                  "server_error": {
                    "value": {
                      "status": false,
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "auth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "Authorization"
      }
    },
    "parameters": {
      "UserId": {
        "name": "id",
        "in": "path",
        "description": "Id of the user to get",
        "required": true,
        "schema": {
          "type": "string"
        },
        "examples": {
          "id": {
            "value": "ce6c992c-f260-4bc9-b332-3e12a10df8fb"
          }
        }
      },
      "ArticleId": {
        "name": "id",
        "in": "path",
        "description": "id of the article to get",
        "required": true,
        "schema": {
          "type": "string"
        },
        "examples": {
          "id": {
            "value": "ce6c992c-f260-4bc9-b332-3e12a10df8fb"
          }
        }
      }
    },
    "schemas": {
      "RequestLogin": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "required": ["email", "password"]
      },
      "ResponseLogin": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "token": {
                "type": "string"
              }
            },
            "required": ["name", "email", "token"]
          }
        }
      },
      "RequestRegister": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "confirm_password": {
            "type": "string"
          }
        },
        "required": ["name", "email", "password", "confirm_password"]
      },
      "ResponseCreateUpdateDelete": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "required": ["status", "message"]
      },
      "ResponseGetUser": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              }
            },
            "required": ["id", "name", "email"]
          }
        }
      },
      "ResponseGetAllUsers": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/ResponseGetUser"
        }
      },
      "RequestUpdateUser": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        }
      },
      "RequestUpdatePasswordUser": {
        "type": "object",
        "properties": {
          "old_password": {
            "type": "string"
          },
          "new_password": {
            "type": "string"
          },
          "confirm_password": {
            "type": "string"
          }
        }
      },
      "ResponseError": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "required": ["status", "message"]
      },
      "ResponseArticle": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        },
        "required": ["id", "title", "description", "image"]
      },
      "NewArticle": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        },
        "required": ["title", "description", "image"]
      }
    }
  }
}
